import type { Config, Service } from './schema';
const app = (
  id: string,
  name: string,
  description: string,
  url: string,
  icon: Service['icon'],
  color: Service['color'],
  group: string,
): Service => ({
  id,
  name,
  description,
  url,
  icon,
  color,
  group,
  check: false,
});
export const defaultConfig: Config = {
  version: 1,
  revision: 0,
  title: 'The Directory',
  theme: 'dark',
  accent: 'mint',
  columns: 3,
  subtitle: 'Everything you need, right where you left it.',
  compact: false,
  backgroundUrl: '',
  customCss: '',
  widgets: ['clock', 'system', 'docker', 'notes'],
  boards: [
    {
      id: 'home',
      name: 'Overview',
      notes:
        'Welcome to your little corner of the internet.\n\nEdit the example services to point to your own homelab, then enable health checks. Make yourself at home.',
      services: [
        app(
          'proxmox',
          'Proxmox',
          'Virtual machines & containers',
          'https://proxmox.home:8006',
          'server',
          'orange',
          'Infrastructure',
        ),
        app(
          'portainer',
          'Portainer',
          'Your containers, under control',
          'https://portainer.home',
          'database',
          'blue',
          'Infrastructure',
        ),
        app(
          'homeassistant',
          'Home Assistant',
          'A smarter place to call home',
          'https://homeassistant.home:8123',
          'home',
          'blue',
          'Infrastructure',
        ),
        app(
          'jellyfin',
          'Jellyfin',
          'Movie night starts here',
          'https://jellyfin.home:8096',
          'play',
          'purple',
          'Media & entertainment',
        ),
        app(
          'sonarr',
          'Sonarr',
          'Keep up with your favorite series',
          'https://sonarr.home:8989',
          'film',
          'blue',
          'Media & entertainment',
        ),
        app(
          'radarr',
          'Radarr',
          'Your next great watch',
          'https://radarr.home:7878',
          'film',
          'orange',
          'Media & entertainment',
        ),
        app(
          'nextcloud',
          'Nextcloud',
          'Your files, wherever you are',
          'https://nextcloud.home',
          'cloud',
          'blue',
          'Everyday essentials',
        ),
        app(
          'adguard',
          'AdGuard Home',
          'A quieter, cleaner internet',
          'https://adguard.home',
          'shield',
          'mint',
          'Everyday essentials',
        ),
        app(
          'gitea',
          'Gitea',
          'A home for your code',
          'https://gitea.home',
          'code',
          'mint',
          'Everyday essentials',
        ),
      ],
    },
  ],
};
