import type { Config, Service } from './schema';
const app = (
  id: string,
  name: string,
  description: string,
  url: string,
  icon: Service['icon'],
  color: Service['color'],
  group: string,
): Service => ({
  id,
  name,
  description,
  url,
  icon,
  color,
  group,
  check: false,
});
export const defaultConfig: Config = {
  version: 1,
  revision: 0,
  title: 'The Directory',
  theme: 'dark',
  accent: 'mint',
  columns: 3,
  subtitle: 'Your self-hosted services.',
  compact: false,
  backgroundUrl: '',
  customCss: '',
  widgets: ['clock', 'system', 'docker', 'notes'],
  boards: [
    {
      id: 'home',
      name: 'Overview',
      notes: 'Edit the example service URLs to connect your homelab.',
      services: [
        app(
          'proxmox',
          'Proxmox',
          'Virtual machines & containers',
          'https://proxmox.home:8006',
          'server',
          'orange',
          'Infrastructure',
        ),
        app(
          'portainer',
          'Portainer',
          'Container management',
          'https://portainer.home',
          'database',
          'blue',
          'Infrastructure',
        ),
        app(
          'homeassistant',
          'Home Assistant',
          'Home automation',
          'https://homeassistant.home:8123',
          'home',
          'blue',
          'Infrastructure',
        ),
        app(
          'jellyfin',
          'Jellyfin',
          'Media library',
          'https://jellyfin.home:8096',
          'play',
          'purple',
          'Media',
        ),
        app(
          'sonarr',
          'Sonarr',
          'TV series',
          'https://sonarr.home:8989',
          'film',
          'blue',
          'Media',
        ),
        app(
          'radarr',
          'Radarr',
          'Movie collection',
          'https://radarr.home:7878',
          'film',
          'orange',
          'Media',
        ),
        app(
          'nextcloud',
          'Nextcloud',
          'Files & collaboration',
          'https://nextcloud.home',
          'cloud',
          'blue',
          'Applications',
        ),
        app(
          'adguard',
          'AdGuard Home',
          'DNS & ad blocking',
          'https://adguard.home',
          'shield',
          'mint',
          'Applications',
        ),
        app(
          'gitea',
          'Gitea',
          'Git repositories',
          'https://gitea.home',
          'code',
          'mint',
          'Applications',
        ),
      ],
    },
  ],
};
